parser: babel-eslint
plugins: []
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  es6: true
  browser: true
  node: true
globals:
  TweenMax: true
rules:
  comma-dangle:
    - 1
    - never
  no-console: 0
  no-debugger: 0
  no-empty: 0
  no-extra-parens: 0
  no-extra-semi: 0
  default-case: 0
  no-alert: 0
  no-empty-function: 0
  no-param-reassign: 0
  no-undef: 0
  no-unused-vars: 0
  max-len:
    - 2
    - 120
    - 2
  max-statements:
    - 2
    - 30
